resolver: lts-5.5

packages:
  - '.'
  - location:
      git: https://gitlab.com/pharpend/semiring-simple.git
      commit: aba18624c5b178e4289ff395743f460c306072b9
    extra-dep: true

extra-deps :
  - aeson-0.10.0.0
